version: 2
updates:
    - package-ecosystem: npm
      directory: '/core-sdk-samples/higgs-shop-sample-app/'
      schedule:
          interval: weekly
          day: 'sunday'
      target-branch: 'chore/dependabot'
      labels: ['dependabot']
      open-pull-requests-limit: 10
      commit-message:
        prefix: "chore"
      allow:
          - dependency-type: 'production'
