name: Daily Cron

# For testing purposes, I'll make this a manual dispatch, but this will become a cron after

on: [ workflow_dispatch ]

  # Run daily at midnight
  # schedule:
  #   - cron: "0 0 * * *"
  
  # Allow to be called from a workflow child  
#   workflow_call: 
#     secrets:
#       MP_DAILY_CRON_BOT:
#         description: 'token needed for stale action'
#         required: true
  
jobs:
    fetch-data-plans:
      name: Fetch Data Plan
      # needs: confirm-public-repo-main-branch
      uses: mParticle/mparticle-workflows/.github/workflows/data-plan-fetch.yml@9fdb40e3112ae43e86fb0817ba6d306dd013e1e0
      with:
        data_plan_id: higgs_shop_basic_data_plan
        data_plan_version: 1
        app_relative_path: core-sdk-samples/higgs-shop-sample-app
      secrets:
        WORKSPACE_ID: ${{ secrets.HIGGS_SHOP_WORKSPACE_ID }}
        CLIENT_ID: ${{ secrets.HIGGS_SHOP_CLIENT_ID }}
        CLIENT_SECRET: ${{ secrets.HIGGS_SHOP_CLIENT_SECRET }}
