name: Sync Data Plan

on: [ workflow_dispatch ]

jobs:
    fetch-data-plan:
      name: Fetch Data Plan
      uses: mParticle/mparticle-workflows/.github/workflows/data-plan-fetch.yml@c0e46586fbba017da4ec55bf6d5b3ae7092c1637
      with:
        data_plan_id: higgs_shop_basic_data_plan
        data_plan_version: 1
        app_relative_path: core-sdk-samples/higgs-shop-sample-app
      secrets:
        WORKSPACE_ID: ${{ secrets.HIGGS_SHOP_WORKSPACE_ID }}
        CLIENT_ID: ${{ secrets.HIGGS_SHOP_CLIENT_ID }}
        CLIENT_SECRET: ${{ secrets.HIGGS_SHOP_CLIENT_SECRET }}
        
    open-pull-request:
      name: Open Pull Request for Data Plan
      runs-on: ubuntu-latest
      needs: fetch-data-plan
      env:
        GIT_AUTHOR_NAME: mparticle-bot
        GIT_AUTHOR_EMAIL: developers@mparticle.com
        GIT_COMMITTER_NAME: mparticle-bot
        GIT_COMMITTER_EMAIL: developers@mparticle.com
      steps:
        - name: Checkout
          uses: actions/checkout@v2
          
        - name: Download Data Plan Artifacts
          uses: actions/download-artifact@v3
          with:
            name: higgs-shop-dataplan
            path: core-sdk-samples/higgs-shop-sample-app/dataplans
            
        - name: Display downloaded files
          run: ls -R
          working-directory: core-sdk-samples/higgs-shop-sample-app/dataplans
          
          
        - name: View Data Plan
          run: cat higgs_shop_basic_data_plan_1.json
          working-directory: core-sdk-samples/higgs-shop-sample-app/dataplans

        - name: Check For Changes
          id: check-changes
          run: |
              if [ `git rev-parse HEAD` = `git rev-parse origin/main` ]; 
              then   
                  OUTPUT=false;
                else 
                  OUTPUT=true;
              fi;
              echo "::set-output name=hasChanges::$OUTPUT"
              echo "has changes: $OUTPUT"

        - name: Open PR if Data Plan Changed
          if: ${{steps.check-changes.outputs.hasChanges == 'true'}}
          uses: actions/github-script@v3
          with:
            github-token: ${{secrets.GITHUB_TOKEN}}
            script: |
              github.pulls.create({
                  title: 'chore: update sdk artifacts',
                  owner: context.repo.owner,
                  repo: context.payload.repository.name,
                  head: 'chore/update-data-plan',
                  base: 'main'
              }); 
